[features]
seeds = false
skip-lint = false
[programs.mainnet]
raffle = "5XSjtXtMJL7iznLMtahrATE7ZdvuVYHxk7Kv77hyP3P5"
auction = "HBCz3iBqcGk45uWLq6MRSpGtJSyazTyERZm3ExGqzXgx"
[programs.devnet]
raffle = "5XSjtXtMJL7iznLMtahrATE7ZdvuVYHxk7Kv77hyP3P5"
auction = "HBCz3iBqcGk45uWLq6MRSpGtJSyazTyERZm3ExGqzXgx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
